### ISSUE TITLE
New allikad.info

### ISSUE THREAD

**Issue by JTerasmaa** [centre-for-educational-technology/wateract#22] opened 2020-11-24 15:21 UTC
Found some bugs :-)
1) Submitted links are directing to the https://allikad.info/springs/....

2) When adding observations the descriptions seems to come from the wrong column of the database or something are "dissolved_oxygen_percentage" etc. Should be "Dissolved oxygen, %". Same with the help text when submitting the spring "'springs.latitude_help_text'".

3) No springs under the map :-)

**Comment by ailimadisson** [comment] 2020-11-24 16:01
1. should direct to springs page? at the moment when creating a new spring, user are directed to springs page and when editing a spring, user are directed to spring view page.

2. at the moment there's no translations thats why those are displayed like that

3. confirmed springs weren't displayed on a map, this should be fixed by now.

**Comment by JTerasmaa** [comment] 2020-11-24 16:26
I mean link to somewhere otuside submitted with spring, directs to the wrong place.
![image](https://user-images.githubusercontent.com/19798405/100122736-6892a800-2e82-11eb-9f79-5b19c11ff266.png)

**Comment by ailimadisson** [comment] 2020-11-24 19:21
ok. the problem seems to be that url title is written in url field and url title is in url field. Need to put a check that checks if url is url.

**Comment by JTerasmaa** [comment] 2020-11-30 06:15
> 2. at the moment there's no translations thats why those are displayed like that

There are all translations and also units in the table. In the worksheet "Allikate_rakenduse_andmebaasi_selgitus"

**Closed** 2021-01-08 10:47 UTC
